# Generated by Django 6.0.5 on 2026-06-03 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='problem',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='review',
            name='solution',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
