# Generated by Django 6.0.5 on 2026-06-03 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_review_problem_review_solution_review_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='problem',
        ),
        migrations.RemoveField(
            model_name='review',
            name='solution',
        ),
    ]
